name: CI - OmniDataLab (Otimizado)

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    name: "Linting e Formatação"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Cache de dependências
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            venv/
          key: lint-${{ runner.os }}-py3.10-${{ hashFiles('requirements-dev.txt') }}
          restore-keys: |
            lint-${{ runner.os }}-py3.10-

      - name: Listar arquivos no repositório
        run: ls -la

      - name: Instalar dependências de desenvolvimento
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt
          python -m pip install psycopg2-binary

      - name: Verificar formatação (Black)
        run: black --check --diff .

      - name: Verificar estilo (Flake8)
        run: flake8 . --show-source --statistics

  test_postgresql_connection:
    name: Teste de Conexão com PostgreSQL
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: Jotta@1440
          POSTGRES_DB: vtex_catalog
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Instalar dependências
        run: |
          pip install psycopg2-binary pytest

      - name: Rodar teste de conexão com o PostgreSQL
        run: |
          python -m pytest tests/integration/test_postgresql_connection.py -p no:cov -c /dev/null

  test:
    name: "Testes (Python ${{ matrix.python-version }})"
    needs: lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            venv/
          key: test-${{ runner.os }}-py${{ matrix.python-version }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            test-${{ runner.os }}-py${{ matrix.python-version }}-

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pytest pytest-cov

  security:
    name: "Verificação de Segurança"
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Verificar vulnerabilidades
        run: |
          python -m pip install safety
          safety check --full-report

  notify:
    name: "Notificação"
    if: false
    needs: [lint, security]
    runs-on: ubuntu-latest
    steps:
      - name: Notificar Slack
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: "danger"
          SLACK_TITLE: "Falha no CI (OmniDataLab)"
          SLACK_MESSAGE: "Falha no workflow ${{ github.workflow }}"
          SLACK_FOOTER: "Commit: ${{ github.sha }} | Detalhes: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

      - name: Notificar sucesso
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: "good"
          SLACK_TITLE: "CI Aprovado (OmniDataLab)"
          SLACK_MESSAGE: "Todos os jobs passaram! 🎉"
          SLACK_FOOTER: "Commit: ${{ github.sha }} | Detalhes: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
